
### Vendored dependencies

OpenResty packages are in `./usr-local-openresty-site/`
— we can Dockerfile COPY from that directory, to install lua-resty-acme
and other packages, when building the Docker image.
No need to run 'opm' (OpenResty Package Manager) and fetch external things from GitHub;
instead, we can build offline (assuming you have the base Docker images).

Apparently this approach is fine — opm installs only pure Lua packages. From
the docs:

> opm currently only supports pure Lua libraries but we will add support for
> Lua libraries in pure C or with some C components very soon

https://opm.openresty.org/docs#description

Meaning, opm downloads just Lua code; it won't compile any C code, or do any
build steps as part of the installation.  So, it's just fine to just Dockerfile COPY
the Lua files.

(In Nodejs, though, some packages start compiling C code via node-gyp when they get installed.)


And Wangchong @fffonion the lua-resty-acme project author agrees:

> Correct, opm only download lua files

https://github.com/fffonion/lua-resty-acme/issues/29



### How to upgrade packages

In docker-compose.yml, uncomment a line that
read-write mounts [an empty directory on the host] in OpenResty's package dir
— search for `[upd_resty_pkgs]` in docker-compose.yml and you'll find the line:

----
      #- ./images/web/openresty-pkgs/new/:/usr/local/openresty/site/
----

After you've uncommented it, start the Web container: `d/c run --rm web bash`

Thereafter, in the Web container, install the OpenResty packages Ty needs.
They'll appear in `./images/web/openresty-pkgs/new/` (on the host):

----
# In the Web container:
opm install fffonion/lua-resty-acme
----

Exit the container.

Git-remove the old packages, and Git-add the new:

----
cd images/web/openresty-pkgs/
git rm -fr ./usr-local-openresty-site
mv ./new ./usr-local-openresty-site
git add ./usr-local-openresty-site
----

Comment out the read-write mount from  in docker-compose.yml again.

Commit. Review the Git diff. Update this submodule (openresty-pkgs) in the main repo.

Lastly, rebuild the Web container, so the new packages get copied into it:

----
# In the project base dir:
s/tyd rebuild web
----

Now you've upgraded the OpenResty pacakges.
